### ISSUE TITLE
Crash when closing Settings window(Unity 2022.3.1.11f1)

### ISSUE THREAD

**Issue by creeper-0910** [CdecPGL/unity-git-version#15]
If you open Settings from the Unity tools and close the window without changing any settings, the Unity Editor crashes.

**Comment by CdecPGL** [comment]
Thank you for your post.
We succeeded to reproduce the problem in Unity 2022.3.11f1.
2022.3.1.11f1

**Comment by CdecPGL** [comment]
Thank you for submitting the issue.
We identified a problem with the settings save process, which was causing crashes in specific versions of Unity.
This issue has been resolved, so please use the latest version of our tool.
If you continue to experience same problem, please reopen this issue.

**Comment by creeper-0910** [comment]
Thanks!
